[colors.primary]
background = "#000000"

[font]
# size=10.5
# size=11.5
# normal={ family = "IosevkaTerm Nerd Font" }
# size=10.5
# normal={ family = "FiraCode Nerd Font" }
size=12
normal={ family = "Inconsolata Nerd Font" }
# size=12
# normal={ family = "UbuntuMono Nerd Font" }
