source = ~/.config/hypr/config/utils.conf
source = ~/.config/hypr/config/programs.conf
source = ~/.config/hypr/config/monitor.conf

source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/theme.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/keyboard.conf
source = ~/.config/hypr/config/mouse.conf
source = ~/.config/hypr/config/windows.conf
source = ~/.config/hypr/config/binds.conf
