$terminal = ghostty
$fileManager = dolphin
$menu = wofi --show drun
$browser = zen
$browser_private = zen --private-window
$lock = hyprlock
$wallpaper = hyprpaper
$statusbar = ~/.config/hypr/scripts/statusbar_toggle.sh
$suspend = ~/.config/hypr/scripts/lock_and_suspend.sh
