$terminal = alacritty
$fileManager = dolphin
$menu = wofi --show drun
$browser = zen
$browser_private = zen --private-window
$statusbar = ~/.local/bin/statusbar_toggle.sh
$lock = hyprlock
$wallpaper = hyprpaper
